### ISSUE TITLE
Downgrading to Java 7

### ISSUE THREAD

**Issue by shantstepanian** [sualeh/SchemaCrawler#120]
Hi, we'd like to leverage schemacrawler; however, we still have a few products on Java 7.

I'd like to see if you are okay with downgrading back to Java 7 - I can contribute the change if so.

It could also help w/ adoption, lowering the barrier to entry, particularly considering many long-lived enterprise applications that are still on older Java versions that are maintained but cannot be upgraded for whatever reason (although yes, folks should have upgraded a while back)

I raise this issue first before submitting my pull request as the main points of contention are around classes like Optional, Duration, Supplier, Predicate, etc. that were only added in JDK 8. If we imported Guava as a library, then many of these classes are available there, but I see that schemacrawler has minimal dependencies.

Thoughts?

**Comment by adriens** [comment]
Seen on https://java.com/en/download/faq/java_7.xml :

 Java 7 Information
Java SE 7 End of Public Updates Notice

> 
After April 2015, Oracle will no longer post updates of Java SE 7 to its public download sites. Existing Java SE 7 downloads already posted as of April 2015 will remain accessible in the Java Archive on the Oracle Technology Network. Developers and end-users are encouraged to update to more recent Java SE versions that remain available for public download in order to continue receiving public updates and

**Comment by sualeh** [comment]
Shant, I have made as many changes as I am comfortable in making to maintain some backward compatibility with Java 7. This should help reduce the changes you will need to make when you back-port, and also help merging in future changes.
